name = input("이름을 입력하시오: ")
print(name, "씨, 안녕하세요?")
print("파이썬에 오신 것을 환영합니다.")
first_integer = int(input("첫 번째 정수를 입력하시오: "))
second_integer = int(input("두 번재 정수를 입력하시오: "))
print(first_integer, "과", second_integer, "의 합은", first_integer + second_integer, "입니다.")
